modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/better-punching/issues"

[[mods]]
modId = "betterpunching"
version = "${file.jarVersion}"
displayName = "Better Punching"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/better-punching"
logoFile = "betterpunching.png"
credits = "Thanks for this mod goes to Java and the Forge Team"
authors = "Darkorg"
description = '''A mod, overhauling punching and breaking mechanics in a popular block game!'''