modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/betterpunching/issues"

[[mods]]
modId = "betterpunching"
version = "${file.jarVersion}"
displayName = "Better Punching"
#updateJSONURL=""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/betterpunching"
logoFile = "betterpunching.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
description = '''A mod, overhauling punching and breaking mechanics in a popular block game!'''
#displayTest=""

[[dependencies.betterpunching]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterpunching]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"